# Generated by Django 4.2.8 on 2024-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('of', 'OFF duty'), ('sb', 'Sleeper berth'), ('dr', 'Driving'), ('on', 'ON duty'), ('pc', 'Persolan conveyance'), ('ym', 'Yarn move')], max_length=2),
        ),
    ]
