# Generated by Django 4.2.8 on 2024-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_access_companies_alter_access_drivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
