# Generated by Django 4.2.8 on 2024-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_driver_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='allow_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='allow_ym',
            field=models.BooleanField(default=False),
        ),
    ]
