# Generated by Django 4.2.8 on 2024-01-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_driver_allow_pc_driver_allow_ym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lng',
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='truck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.truck'),
        ),
        migrations.AlterField(
            model_name='location',
            name='adress',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='log',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('of', 'OFF duty'), ('sb', 'Sleeper berth'), ('dr', 'Driving'), ('on', 'ON duty'), ('pc', 'Persolan conveyance'), ('ym', 'Yarn move')], default='of', max_length=2),
        ),
    ]
