# Generated by Django 4.2.8 on 2024-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_log_lat_remove_log_lng_location_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress',
            new_name='address',
        ),
    ]
