# Step 1: build stage
FROM node:18-alpine

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
ENTRYPOINT [ "echo", "finished" ]
# RUN npm run build
# RUN npm run build

# Step 2: production stage
# FROM nginx:1.25-alpine

# COPY --from=build-stage /app/dist /usr/share/nginx/html
# EXPOSE 80
# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]