version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 3000:3000

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 8000:8000
    restart: on-failure
    command: ./docker-entrypoint.sh

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=inteleld_db
      - MYSQL_ROOT_PASSWORD=MyPassword
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:

  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379
  #   restart: always
  #   volumes:
  #     - redisdata:/data
  # smtp4dev:
  #   image: rnwood/smtp4dev:v3
  #   ports:
  #     - 5000:80
  #     - 25:25
  #   restart: always
  # celery:
  #   build: .
  #   command: poetry run celery -A core worker --loglevel=info
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  # celery-beat:
  #   build: .
  #   command: poetry run celery -A core beat --loglevel=info
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  # flower:
  #   build: .
  #   command: poetry run celery -A core flower
  #   depends_on:
  #     - web
  #     - redis
  #     - celery
  #   environment:
  #     - DEBUG=1
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   ports:
  #     - 5555:5555
  # tests:
  #   build: .
  #   command: ./wait-for-it.sh mysql:3306 -- ptw
  #   depends_on:
  #     - redis
  #     - mysql
  #   tty: true
  #   volumes:
  #     - .:/app
# volumes:
#   mysqldata:
# pgdata:
# redisdata:
