# Generated by Django 4.2.8 on 2024-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='companies',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='access',
            name='drivers',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='access',
            name='logs',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='access',
            name='trucks',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='access',
            name='users',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
