# Generated by Django 4.2.8 on 2024-01-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.access'),
        ),
    ]
