# Generated by Django 4.2.8 on 2024-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('own', 'Owner'), ('dis', 'Dispatcher'), ('upd', 'Updater'), ('flm', 'Fleet manager'), ('sam', 'Safety manager'), ('acc', 'Accountant'), ('gue', 'Guest')], max_length=3, null=True),
        ),
    ]
